server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/video?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  cloud:
    nacos:
      # Nacos 服务注册发现
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
      # Seata 事务组名称，对应file.conf文件中 vgroup_mapping.sca-customer-seata-tx-service-group
        tx-service-group: sca-customer-group
  application:
    name: sca-customer
mybatis:
  mapper-locations: classpath:mapper/*.xml



