spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dutyk/kotlinmicroservice
          username: dutyk
          password: yk13579/
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录
server:
  port: 8060